//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoSubmit.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoSubmit.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 function doLogin() {
        ///    var loginid = $.trim(document.loginform.loginid.value); //登录ID
        ///    var password = document.loginform.password.value; //密码
        ///    var vcode = document.loginform.vcode.value;		 //验证码
        ///    var isCa = &quot;false&quot;;
        ///    if ($(&quot;#isCa&quot;).attr(&quot;checked&quot;)) {
        ///        isCa = document.loginform.isCa.value;		 //是否CA登录
        ///        if (password == &quot;&quot; || password == undefined) {
        ///            $(&quot;#isCa&quot;).attr(&quot;checked&quot;, false);
        ///            GGFW.alert(&quot;请输入证书密码&quot;);
        ///            document.loginform.password.foc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DoLoginJS {
            get {
                return ResourceManager.GetString("DoLoginJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function getLoginPostData(){var loginid = $.trim(document.loginform.loginid.value); //登录ID
        ///        var password = document.loginform.password.value; //密码
        ///        var vcode = document.loginform.vcode.value;		 //验证码
        ///        var isCa = &quot;false&quot;;
        ///        if ($(&quot;#isCa&quot;).attr(&quot;checked&quot;)) {
        ///            isCa = document.loginform.isCa.value;		 //是否CA登录
        ///            if (password == &quot;&quot; || password == undefined) {
        ///                $(&quot;#isCa&quot;).attr(&quot;checked&quot;, false);
        ///                GGFW.alert(&quot;请输入证书密码&quot;);
        ///          [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetLoginPostDataJS {
            get {
                return ResourceManager.GetString("GetLoginPostDataJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;FORM name=linkform id=linkform action=/gdweb/ggfw/web/wsyw/wsyw.do method=post target=_blank&gt;&lt;INPUT name=cmenuid type=hidden jQuery18305867853768845443=&quot;5&quot; value=170201&gt; &lt;INPUT name=MenuId type=hidden value=9999 jQuery18305867853768845443=&quot;7&quot;&gt; &lt;INPUT name=SUBSYS type=hidden value=LDL jQuery18305867853768845443=&quot;8&quot;&gt;&lt;/FORM&gt; 的本地化字符串。
        /// </summary>
        internal static string GoToSubmitPageHTML {
            get {
                return ResourceManager.GetString("GoToSubmitPageHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function goToSubmitPage(){
        ///            document.linkform.target = &quot;_self&quot;;
        ///            document.linkform.submit();} 的本地化字符串。
        /// </summary>
        internal static string GotoSubmitPageJS {
            get {
                return ResourceManager.GetString("GotoSubmitPageJS", resourceCulture);
            }
        }
    }
}
